### ISSUE TITLE
Issue with Azure B2C AD

### ISSUE THREAD

**Issue by TauTauBenn** [ImperialPlugins/steam-openid-connect-provider#10]
Getting the following error when configuring the openid-connect-provider in Azure AD: "A claim with id \'UserId\' was not found, which is required by ClaimsTransformation \'CreateAlternativeSecurityId\' with id \'CreateAlternativeSecurityId\'"

Azure AD Settings:
![image](https://user-images.githubusercontent.com/85042590/120088101-d8ae0f00-c0ed-11eb-936e-af852245f2df.png)

I'm using the docker container and there i get the message: 
2021-05-30T00:23:33.071140683Z: [INFO]  [00:23:33 Debug] IdentityServer4.Services.DefaultClaimsService
2021-05-30T00:23:33.071176985Z: [INFO]  In addition to an id_token, an access_token was requested. No claims other than sub are included in the id_token. To obtain more user claims, either use the user info endpoint or set AlwaysIncludeUserClaimsInIdToken on the client configuration.

Maybe this is why Azure AD has no access to the required claims?

**Comment by saskenuba** [comment]
Not sure if you have this issue anymore, but I've solved mine with this diff on my fork

https://github.com/saskenuba/steam-openid-connect-provider/commit/c6136cedbc52a7fd4b6417a8e4f73f11392e489d?w=1&diff=split

**Comment by Trojaner** [comment]
@saskenuba can you do a PR?

**Comment by saskenuba** [comment]
> @saskenuba can you do a PR?

hey, I've rebased my branch and opened the pr #13

**Comment by TauTauBenn** [comment]
Thanks for the fix, could you possibly update the docker container? :)

**Comment by Trojaner** [comment]
Sadly DockerHub shut down autobuilds for the free tier, so we need to switch to GitHub actions instead. However at the moment I don't have time to work on that
