### ISSUE TITLE
How to get other claims besides sub, preferred_username and name?

### ISSUE THREAD

**Issue by SunriseM** [ImperialPlugins/steam-openid-connect-provider#6]
I tried to map the picture claim in the profile scope but it wasn't getting saved. Only the sub and username properties. So, I checked the console and found this:

```
steam_1     | [17:00:21 Debug] IdentityServer4.ResponseHandling.UserInfoResponseGenerator
steam_1     | Requested claim types: sub name family_name given_name middle_name nickname preferred_username profile picture website gender birthdate zoneinfo locale updated_at
steam_1     | 
steam_1     | [17:00:21 Debug] IdentityServer4.ResponseHandling.UserInfoResponseGenerator
steam_1     | Scopes in access token: openid profile
steam_1     | 
steam_1     | [17:00:21 Information] IdentityServer4.ResponseHandling.UserInfoResponseGenerator
steam_1     | Profile service returned the following claim types: sub preferred_username name
```

Apparently the picture and other claims are being requested but only sub, preferred_username and name are being returned.

Is it possible to get those claims?

**Comment by Trojaner** [comment]
Valve does not expose the other claims, hence it is not possible.

**Comment by SunriseM** [comment]
What if we use `https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=&steamids` to manually insert the other claims? 

It would give us the picture, given_name, nickname and maybe others claims. I could do it on my app but it would be great if it was just managed by the provider.

**Comment by Trojaner** [comment]
Sadly I do not have the time to work on that, but I would happily accept contributions for it.
